# Dockerfile.dev
FROM node:20-alpine

# Create application directory
WORKDIR /app

# Install system dependencies
RUN apk add --no-cache \
    python3 \
    make \
    g++ \
    postgresql-client

# Copy configuration files
COPY package*.json ./
COPY tsconfig*.json ./

# Install dependencies
RUN npm ci

# Copy source code
COPY . .

# Expose port
EXPOSE 3000 9229

# Default command
CMD ["npm", "run", "start:dev"]