name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  NODE_VERSION: '18'
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/api

jobs:
  # Frontend Tests
  frontend-tests:
    name: Frontend Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: './src/frontend/package-lock.json'

      - name: Setup Chrome for testing
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests (headless)
        run: npm test -- --browsers=ChromeHeadless --watch=false --code-coverage

      - name: Build application
        run: npm run build

      - name: Upload frontend build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: src/frontend/dist/
          retention-days: 1

  # Backend Tests
  api-tests:
    name: Backend Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/api

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_PASSWORD: test_password
          POSTGRES_USER: test_user
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: './src/api/package-lock.json'

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Install dependencies
        run: npm ci

      - name: Verify database connectivity
        run: |
          echo "Testing database connection..."
          pg_isready -h localhost -p 5432 -U test_user
          echo "Database services status:"
          docker ps --filter "label=com.docker.compose.service=postgres" || echo "No Docker services found"

      - name: Run linting
        run: npm run lint

      - name: Run unit tests
        run: npm run test:ci
        env:
          DATABASE_HOST: localhost
          DATABASE_PORT: 5432
          DATABASE_USERNAME: test_user
          DATABASE_PASSWORD: test_password
          DATABASE_NAME: test_db
          JWT_ACCESS_SECRET: test-jwt-secret-for-ci
          JWT_REFRESH_SECRET: test-refresh-secret-for-ci
          NODE_ENV: test

      - name: Upload test coverage
        uses: codecov/codecov-action@v3
        with:
          file: ./src/api/coverage/lcov.info
          directory: ./src/api/coverage
          flags: api

      - name: Build application
        run: npm run build

      - name: Run production readiness check
        run: |
          cp .env.example .env.production
          ./scripts/check-production-readiness.sh || true

  # Security Scanning
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: [api-tests]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Backend security scan
      - name: Backend security audit
        working-directory: ./src/api
        run: |
          npm audit --audit-level=high
          npx audit-ci --high

      # Frontend security scan
      - name: Frontend security audit
        working-directory: ./src/frontend
        run: |
          npm audit --audit-level=high
          npx audit-ci --high

      - name: Run Snyk security scan
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

      - name: Run CodeQL analysis
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@v3

  # Database Migration Tests
  migration-tests:
    name: Database Migration Tests
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    defaults:
      run:
        working-directory: ./src/api

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_PASSWORD: test_password
          POSTGRES_USER: test_user
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: './src/api/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Test migrations
        run: |
          npm run migration:run
          npm run migration:revert
        env:
          DATABASE_HOST: localhost
          DATABASE_PORT: 5432
          DATABASE_USERNAME: test_user
          DATABASE_PASSWORD: test_password
          DATABASE_NAME: test_db

  # Docker Build Test
  docker-build:
    name: Docker Build Test
    runs-on: ubuntu-latest
    needs: [api-tests, frontend-tests]
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build API Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./src/api
          file: ./src/api/Dockerfile
          push: false
          tags: allodoc-api:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test Docker image
        run: |
          docker run --name test-api -d -p 3000:3000 \
            -e NODE_ENV=production \
            -e DATABASE_HOST=localhost \
            -e JWT_ACCESS_SECRET=test-secret \
            allodoc-api:test
          
          sleep 10
          
          # Test health endpoint
          curl -f http://localhost:3000/health || exit 1
          
          docker stop test-api

  # Integration Tests
  e2e-tests:
    name: End-to-End Tests
    runs-on: ubuntu-latest
    needs: [api-tests, frontend-tests]
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Start services with Docker Compose
        run: |
          cp src/api/.env.example src/api/.env
          docker-compose -f infrastructure/docker/docker-compose.dev.yml up -d
          sleep 30

      - name: Install E2E test dependencies
        working-directory: ./src/frontend
        run: npm ci

      # TODO: Configure E2E testing framework (Cypress/Playwright)
      # - name: Run E2E tests
      #   working-directory: ./src/frontend
      #   run: npm run e2e:ci

      - name: Upload E2E test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-results
          path: |
            src/frontend/e2e/screenshots/
            src/frontend/e2e/videos/

      - name: Stop services
        if: always()
        run: docker-compose -f infrastructure/docker/docker-compose.dev.yml down

  # Build and Push Images (on main branch)
  build-and-push:
    name: Build and Push Images
    runs-on: ubuntu-latest
    needs: [api-tests, frontend-tests, security-scan]
    if: github.ref == 'refs/heads/main'

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-
            type=raw,value=latest

      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: ./src/api
          file: ./src/api/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # Performance Tests
  performance-tests:
    name: Performance Tests
    runs-on: ubuntu-latest
    needs: [build-and-push]
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Artillery
        run: npm install -g artillery@latest

      - name: Start test environment
        run: |
          cp src/api/.env.example src/api/.env
          docker-compose -f infrastructure/docker/docker-compose.dev.yml up -d
          sleep 30

      - name: Run load tests
        run: |
          cd src/api
          artillery run tests/load/basic-load-test.yml --output report.json

      - name: Generate performance report
        run: |
          cd src/api
          artillery report report.json --output performance-report.html

      - name: Upload performance results
        uses: actions/upload-artifact@v4
        with:
          name: performance-report
          path: src/api/performance-report.html

      - name: Stop services
        if: always()
        run: docker-compose -f infrastructure/docker/docker-compose.dev.yml down